"""Render a gitfault analysis as GitHub-flavoured Markdown.

Markdown renders inline in GitHub issues, PRs and READMEs — so this is the
most shareable output format: `gitfault markdown >> REPORT.md`, or paste it
straight into an issue. It is also the basis for the PR-comment GitHub Action.
"""
from __future__ import annotations

import os
from datetime import datetime

from . import analysis as A


def _short(path: str, width: int = 48) -> str:
    if len(path) <= width:
        return path
    head = width - 3
    return "…" + path[-head:]


def _date(d: datetime) -> str:
    return d.strftime("%Y-%m-%d")


def _bar(frac: float, width: int = 10) -> str:
    frac = max(0.0, min(1.0, frac))
    filled = round(frac * width)
    return "█" * filled + "·" * (width - filled)


def build_markdown(root: str, o: A.Overview, hs, cp, k, top: int = 20) -> str:
    name = os.path.basename(os.path.abspath(root)) or root
    lines: list[str] = []
    add = lines.append

    add(f"# gitfault report — `{name}`")
    add("")
    add("> Behavioural code analysis from git history — "
        "hotspots, change-coupling and knowledge risk. "
        "Generated by [gitfault](https://pypi.org/project/gitfault/).")
    add("")

    # ---- overview -------------------------------------------------------
    span_days = max((o.last - o.first).days, 1)
    add("## Overview")
    add("")
    add("| metric | value |")
    add("| --- | --- |")
    add(f"| commits | {o.commits:,} |")
    add(f"| authors | {o.authors:,} |")
    add(f"| files tracked | {o.files_tracked:,} |")
    add(f"| history | {_date(o.first)} → {_date(o.last)} ({span_days:,} days) |")
    add(f"| busiest month | {o.busiest_month[0]} ({o.busiest_month[1]:,} commits) |")
    add("")

    # ---- hotspots -------------------------------------------------------
    add("## 🔥 Hotspots")
    add("")
    add("Files ranked by change-frequency × size — where complexity and churn "
        "collide. These deserve tests, review and refactoring attention first.")
    add("")
    if hs:
        add("| # | file | revisions | churn | lines | authors | last change | score |")
        add("| --: | --- | --: | --: | --: | --: | --- | --- |")
        for i, h in enumerate(hs[:top], 1):
            add(f"| {i} | `{_short(h.path)}` | {h.revisions:,} | {h.churn:,} | "
                f"{h.lines:,} | {h.authors} | {_date(h.last_change)} | "
                f"`{_bar(h.score)}` {h.score:.2f} |")
    else:
        add("_No hotspots found._")
    add("")

    # ---- coupling -------------------------------------------------------
    add("## 🔗 Change coupling")
    add("")
    add("File pairs that keep changing together. High coupling between files in "
        "different modules is a hidden dependency — a change in one silently "
        "demands a change in the other.")
    add("")
    if cp:
        add("| # | file A | file B | shared commits | coupling |")
        add("| --: | --- | --- | --: | --- |")
        for i, c in enumerate(cp[:top], 1):
            add(f"| {i} | `{_short(c.a, 36)}` | `{_short(c.b, 36)}` | "
                f"{c.shared:,} | `{_bar(c.degree)}` {c.degree:.0%} |")
    else:
        add("_No significant coupling found._")
    add("")

    # ---- knowledge ------------------------------------------------------
    add("## 🧠 Knowledge & bus factor")
    add("")
    pct_solo = (k.solo_owned_lines / k.total_lines) if k.total_lines else 0
    add(f"- **Bus factor: {k.bus_factor}** — the number of authors who together "
        f"own the majority of the code. A low number is a key-person risk.")
    add(f"- **{k.total_authors:,}** contributing authors overall.")
    add(f"- **{pct_solo:.0%}** of tracked lines live in files touched by a "
        f"single author.")
    add("")
    if k.top_authors:
        add("### Top knowledge holders")
        add("")
        add("| author | lines owned |")
        add("| --- | --: |")
        for author, owned in k.top_authors[:min(top, 15)]:
            add(f"| {author} | {owned:,} |")
        add("")
    if k.files:
        add("### Most single-author-owned files")
        add("")
        add("| file | main author | ownership | authors | lines |")
        add("| --- | --- | --- | --: | --: |")
        for f in k.files[:top]:
            add(f"| `{_short(f.path)}` | {f.main_author} | "
                f"`{_bar(f.main_share)}` {f.main_share:.0%} | {f.authors} | "
                f"{f.lines:,} |")
        add("")

    add("---")
    add("")
    add("<sub>Generated by **gitfault** · "
        "`pipx install gitfault` · built and maintained by an AI agent "
        "(Kenji Rasmussen).</sub>")
    add("")
    return "\n".join(lines)
